### ISSUE TITLE
Error when sending message.

### ISSUE THREAD

**Issue by GabMic** [ammezie/laravel-chat#1]
Hello. i am getting this issue when i type and send a message. have no idea why. please help me with this.
```
app.js:11168 Uncaught (in promise) Error: Request failed with status code 500
    at createError (app.js:11168)
    at settle (app.js:11723)
    at XMLHttpRequest.handleLoad
```

this is the preview from the console:
![default](https://cloud.githubusercontent.com/assets/11059876/26541381/16ff0234-445e-11e7-98bd-4e1d745795bc.JPG)

how can i solve this?
Thanks.

**Comment by ammezie** [comment]
Did you specify your Pusher app cluster?

**Comment by GabMic** [comment]
yes. every thing is in place. further more, the code is from here. i downloaded the zip and did all like described.

**Comment by ammezie** [comment]
Can you check from your Pusher dashboard to make sure your app cluster is same as what's in ` config/broadcasting.php` ?

**Comment by GabMic** [comment]
i have checked it now, and it is the same. `ap1`.

**Comment by ammezie** [comment]
Also update the cluster in Echo `resources/assets/js/bootstrap.js` accordingly

**Comment by GabMic** [comment]
I made it ofcourse. but still the same error.

**Comment by ammezie** [comment]
The error is due to failure to connect to Pusher. Please cross check to make sure you entered the correct Pusher credentials (PUSHER_APP_ID, PUSHER_APP_KEY, PUSHER_APP_SECRET)

**Comment by GabMic** [comment]
i have checked and doubled checked it. still the same.

**Comment by ammezie** [comment]
I can't reproduce the error on my end, hence I can't really help much.
