### ISSUE TITLE
Pushthis Implementation 

### ISSUE THREAD

**Issue by yordadev** [ammezie/laravel-chat#10]
I have created a Pusher clone and charging 50% less as Pusher is ridiculously expensive; Just about into beta for it. Wondering if I can do a pull request and add in my Laravel package to this once the beta is live. 

My package doesn't use Laravel broadcasting, so you can send data from a controller, trait or an event!

```        
Use Pushthis\Pushthis;

$pushthis->send([
            'channel' => 'example-channel',
            'event' => 'example-event',
            'data' => [
                'message' => 'Hello World'
            ]
        ]);


.env
PUSHTHIS_KEY
PUSHTHIS_SECRET
PUSHTHIS_NETWORK

**Comment by ammezie** [comment]
Great work with Pushthis! Sending a PR to this effect won't be accepted as the `laravel-chat` project was specifically made for Pusher. However, you are free to fork the project and add your implementation with Pushthis.
