### ISSUE TITLE
addMessage error

### ISSUE THREAD

**Issue by lstables** [ammezie/laravel-chat#17]
I have vue components setup and all is good but sending the message I get this error:

<img width="663" alt="screen shot 2018-08-11 at 16 22 08" src="https://user-images.githubusercontent.com/1168291/43993289-d2689976-9d82-11e8-9492-5a643097a05d.png">

Any reason for this?

**Comment by lstables** [comment]
@ammezie Can you advise please?

**Comment by jeremykenedy** [comment]
The component was rendering before the global vue with that method.

It was defined in the to emit from chat.blade.php on line 15.
