### ISSUE TITLE
database

### ISSUE THREAD

**Issue by jayeshsojitra** [ammezie/laravel-chat#3]
hello thanks for this project but i need a database for this project

**Comment by ammezie** [comment]
I don't get your question

**Comment by jayeshsojitra** [comment]
i need databse that are use in this project

when i run this project its give me error
please check http://www.awesomescreenshot.com/image/2597014/7154a1cd8147d3cb82a0648856dd4d27

**Comment by ammezie** [comment]
You need to add your database details in `.env` file  and run `php artisan migrate` to run the migrations.

**Comment by jayeshsojitra** [comment]
but i have no databse

**Comment by jayeshsojitra** [comment]
when i fired php artisan migrate command that give me error
**

> "Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`)) "

**

**Comment by ammezie** [comment]
You will have to create a database then use it details in `.env`

**Comment by ammezie** [comment]
Checkout https://laravel-news.com/laravel-5-4-key-too-long-error to resolve that error

**Comment by jayeshsojitra** [comment]
thanks

**Comment by wadereynes** [comment]
config/database change 
'charset' => 'utf8',
 'collation' => 'utf8_unicode_ci',
