### ISSUE TITLE
Pusher is not defined after upgrade

### ISSUE THREAD

**Issue by pet1330** [ammezie/laravel-chat#4]
Hi,

I managed to run your application by following the steps:

```bash
$ git clone https://github.com/ammezie/laravel-chat
$ composer install
$ cp .env.example .env
$ vim .env
$ php artisan key:generate
$ php artisan migrate
$ yarn
$ yarn run dev
$ php artisan serve
```

And up to this point, everything works fine and I get live updates when messages are sent. However, if I then try to modify it, i.e. by running `yarn upgrade` or even just doing `yarn add moment` (as an example) the whole thing breaks and I get an error message saying `Pusher is not defined`.

Do you have any idea why this might be happening or how I can resolve it?
Thanks

**Comment by ammezie** [comment]
At what point are you getting the error?

**Comment by ammezie** [comment]
I'm closing this as a result of no response.

**Comment by gthuo** [comment]
Had the error and solved it like this: add `window.Pusher = require('pusher-js');` to your bootstrap.js. @ammezie you can help us by editing the code to reflect that.
