### ISSUE TITLE
input form and send button is hidden

### ISSUE THREAD

**Issue by mombe090** [ammezie/laravel-chat#6]
Please first congratulation and think for this tools. I have integrated it with this tutorial https://blog.pusher.com/how-to-build-a-laravel-chat-app-with-pusher/ but the input and the send button is hidden. Thanks to answer as soon as possible it's important for me

**Comment by ammezie** [comment]
Are you having some errors or something? Try looking at the console and vue-dev tool if you have it installed.

**Comment by mombe090** [comment]
No errors the npm run dev gives this
 DONE  Compiled successfully in 8635ms    
But if i expect into my browser, here is the errors 
Vue is not defined 
Object.defineProperty.value @ app.js:855__webpack_require__ 
@ app.js:20(anonymous function) 
@ app.js:845__webpack_require__ 
@ app.js:20(anonymous function)
 @ app.js:63(anonymous function) @ app.js:66
thanks to help me

**Comment by mombe090** [comment]
Think for ur answer i have fix it after 2days hard work

**Comment by ammezie** [comment]
Oh cool! Mind sharing how you fixed it in case others encounter same error.

**Comment by mombe090** [comment]
Ok with the laravel 5.5 by default in the bootstrap.js file the vue include was missing.
By comparing ur codes and mine i saw it?
window.Vue = require('vue'); #was missing so vue library was not loading and compile to the app.js file.

**Comment by DaniGuzman** [comment]
hey, mine says Pusher and Laravel not defined , any help?
